# Generated by Django 4.2 on 2023-12-14 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0006_rename_payment_status_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
