# Generated by Django 4.2 on 2023-12-14 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_remove_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
